version: '3.4'

services:
    mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        ports:
          - "3036:3036"
        networks:
            - microservices
        volumes:
          - mysql-db:/var/lib/mysql

    business-service-customer:
        image: placidenduwayo1/business-service-customer:latest
        container_name: business-service-customer
        build:
            context: ../business-service-customer
            dockerfile: Dockerfile
        ports:
              - "8085:8085"
        networks:
            - micro-services

    business-service-account:
        image: placidenduwayo1/business-service-account:latest
        container_name: business-service-account
        build:
            context: ../business-service-account
            dockerfile: Dockerfile
        ports:
            - "8086:8086"
        networks:
            - microservices

    micro-service-movement:
        image: placidenduwayo1/business-service-movement:latest
        container_name: business-service-movement
        build:
            context: ../business-service-movement
            dockerfile: Dockerfile
        ports:
            - "8087:8087"
        networks:
            - microservices
volumes:
    mysql-db:
networks:
    microservices: